### ISSUE TITLE
Working With API's?

### ISSUE THREAD

**Issue by billh93** [zarocknz/javascript-winwheel#22]
Hey this is not an issue with the code itself. It's more of a question on how to incorporate API's to show on the segments. I managed to insert the object within the array to the winwheel segments key:value pair but I still get errors as it does not load. I get `Uncaught TypeError: Cannot read property 'fillStyle' of undefined`.

I have a repo with all of my work but the code is not pretty. It is somewhat short though 200+ lines of code so hopefully you can just tell me what am I doing wrong and how I can make the data load from my Google Places API.

Here is the link to my [repo](https://github.com/billh93/GrubDecider)

Thanks!

**Comment by zarocknz** [comment]
Hi @billh93,

Thanks for getting in touch. I have just had a quick look over the code in wheel.js in your repo and I see there is this line segments.push(slicePrizes[i]); which is adding the segments to the wheel.

That may be the cause of the problem because adding segments to the wheel has a bit more to it than just adding things to the segments array. Please consider using the addSegment() function, or take a look at what it does and ensure your code replicates that - i.e. creating a Segment object and also updating the numSegments and calling the updateSegmentSizes() function.

Regards,
DouG.

**Comment by billh93** [comment]
Hey @zarocknz!

Thanks for the fast response! Yeah, I assumed it had to do something with the original file. In the console I kept seeing several key:value pairs that weren't originally in the wheel.js file well thanks man!
