### ISSUE TITLE
Option for uploading center image (logo of the company may be) for hollow wheels (doughnuts)

### ISSUE THREAD

**Issue by MJunaidAhmad** [zarocknz/javascript-winwheel#41]
Hi,

I am using wineheel.js for my project and I would like to have the option that my clients may upload their company logo and it will be set at the center of the wheel (of course if it's a hollow wheel). Now, can anybody please guide me how can I modify this library in order to have this feature? Because I don't think for now this library have this feature.

Regards,
Junaid

**Comment by zarocknz** [comment]
Hi @MJunaidAhmad,

One of the example wheels already does something similar - shows a picture though the center of a hollow wheel. Take a look at http://dougtesting.net/winwheel/examples/hollow_wheel

This works by adding a image behind the canvas, then because the wheel is hollow it shows through. Wheel backgrounds are talked about in this tutorial http://dougtesting.net/winwheel/docs/tut10_pointers_and_backgrounds, though in your case instead of using the css background-image property you might want to put an actual image behind the wheel canvas and absolute position things over each other.

As for you clients being able to upload images, that will need to be done with a server-side coding language like PHP. I am sure there are many tutorials out there on uploading an image with PHP.

Regards,
DouG.

**Comment by MJunaidAhmad** [comment]
Thanks for your response. I got the idea. :)
