### ISSUE TITLE
Use WinWheel with ReactJS

### ISSUE THREAD

**Issue by chetanzalake** [zarocknz/javascript-winwheel#51]
Can I use this js file in ReactJS?

**Comment by zarocknz** [comment]
@chetanzalake I honestly don't know as I am not familiar with modern JS frameworks.

Since Winwheel.js is plain JavaScript I imagine it could be included in ReactJS like any other plain JS. I know some people have taken forks of this module and got it working with Angular, for example https://github.com/ipengyo/angular-winwheel/blob/master/Winwheel.js maybe that will give you some ideas.
