### ISSUE TITLE
Can i assign css to the pin?

### ISSUE THREAD

**Issue by Anthony-david** [zarocknz/javascript-winwheel#86]
Can i assign css to the pin?

**Comment by zarocknz** [comment]
No, because nothing on the canvas is an HTML element; its all just lines and shapes drawn on a canvas like drawing something in MS paint or on a bit of paper with a pen.

Winwheel.js is a purely JavaScript and canvas solution. If you would like an HTML and CSS winning wheel I suggest searching for alternatives.

I just did a quick google search for "html and css wheel of fortune" and the top result was this http://bl.ocks.org/jrue/a2aaf36b3c096925ccbf I see it uses HTML elements you should be able to style with CSS.
